name: Django Testing and Deploy

#Указываем условиясрабатывания workflow
on:
  push:
    branches: [master]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: admin
      POSTGRES_PASS: admin
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: cicd_db
      SECRET_KEY: django-insecure-c-1%_g181t6@a=ww4nyu55!3_t#b&efh2p7)^d)raewqow!68%
      ALLOWED_HOSTS: localhost,127.0.0.1
    services:
      postgres_main:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASS }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports: 
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Проверяем наш репозиторий GIT на наличие изменений
        uses: actions/checkout@v2

      - name: Установка python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Установка зависимостей
        run: python -m pip install --upgrade pip

      - name: Установка библиотек
        run: pip install -r requirements.txt

      - name: Линтинг кода (проверка на соответствие РЕР8)
        run: flake8 logistic

      - name: Тестирование
        run: pytest
        env:
          SECRET_KEY: ${{ env.SECRET_KEY }}
          DEBUG: "0"
          ALLOWED_HOSTS: ${{ env.ALLOWED_HOSTS }}
          DB_ENGINE: django.db.backends.postgresql
          DB_NAME: ${{ env.POSTGRES_DB }}
          DB_USER: ${{ env.POSTGRES_USER }}
          DB_PASSWORD: ${{ env.POSTGRES_PASS }}
          DB_HOST: ${{ env.POSTGRES_HOST }}
          DB_PORT: ${{ env.POSTGRES_PORT }}
